# Generated by Django 4.1.3 on 2023-03-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruit", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="position",
            options={
                "ordering": ["created"],
                "verbose_name": "Position",
                "verbose_name_plural": "Positions",
            },
        ),
        migrations.AlterField(
            model_name="position",
            name="position",
            field=models.CharField(default="", max_length=50),
        ),
    ]
