# Generated by Django 4.1.3 on 2023-03-13 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recruit", "0002_alter_position_options_alter_position_position"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="techskill",
            options={
                "ordering": ["created"],
                "verbose_name": "Techskill",
                "verbose_name_plural": "Techskills",
            },
        ),
        migrations.RemoveField(
            model_name="recruit_position",
            name="description",
        ),
        migrations.RemoveField(
            model_name="recruit_position",
            name="title",
        ),
        migrations.RemoveField(
            model_name="recruit_techskill",
            name="description",
        ),
        migrations.RemoveField(
            model_name="recruit_techskill",
            name="title",
        ),
        migrations.RemoveField(
            model_name="techskill",
            name="description",
        ),
        migrations.RemoveField(
            model_name="techskill",
            name="title",
        ),
        migrations.AddField(
            model_name="techskill",
            name="techskill",
            field=models.CharField(default=" ", max_length=200),
        ),
        migrations.AlterField(
            model_name="recruit_techskill",
            name="techskill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Techskill",
                to="recruit.techskill",
            ),
        ),
    ]
