# Generated by Django 4.1.3 on 2023-03-05 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recruit", "0002_alter_recruit_recruit_member"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="position",
            name="description",
        ),
        migrations.RemoveField(
            model_name="position",
            name="title",
        ),
        migrations.AlterField(
            model_name="recruit_techskill",
            name="recruit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recruitTechskill",
                to="recruit.recruit",
            ),
        ),
        migrations.AlterField(
            model_name="recruit_techskill",
            name="techskill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="techSkill",
                to="recruit.techskill",
            ),
        ),
    ]
