# Generated by Django 4.1.3 on 2023-03-28 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruit", "0003_alter_techskill_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recruit",
            name="dday",
        ),
        migrations.RemoveField(
            model_name="recruit",
            name="end",
        ),
        migrations.RemoveField(
            model_name="recruit",
            name="is_remote",
        ),
        migrations.RemoveField(
            model_name="recruit",
            name="start",
        ),
        migrations.RemoveField(
            model_name="recruit",
            name="types",
        ),
    ]
