# Generated by Django 4.1.3 on 2023-03-06 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recruit", "0003_remove_position_description_remove_position_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruit_position",
            name="position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="positions",
                to="recruit.position",
            ),
        ),
        migrations.AlterField(
            model_name="recruit_position",
            name="recruit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recruitPosition",
                to="recruit.recruit",
            ),
        ),
        migrations.AlterField(
            model_name="recruit_techskill",
            name="techskill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="TechSkill",
                to="recruit.techskill",
            ),
        ),
    ]
