# Generated by Django 4.1.3 on 2023-03-06 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruit", "0004_alter_recruit_position_position_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recruit",
            old_name="remote",
            new_name="is_remote",
        ),
    ]
