# Generated by Django 4.1.3 on 2023-03-06 19:49

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("recruit", "0005_rename_remote_recruit_is_remote"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruit",
            name="dday",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="recruit",
            name="likes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="recruit",
            name="view",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="recruitComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")],
                        default=1,
                        verbose_name="status",
                    ),
                ),
                (
                    "activate_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="keep empty for an immediate activation",
                        null=True,
                    ),
                ),
                (
                    "deactivate_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="keep empty for indefinite activation",
                        null=True,
                    ),
                ),
                (
                    "recruit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recruitName",
                        to="recruit.recruit",
                    ),
                ),
            ],
            options={
                "ordering": ["created"],
            },
        ),
    ]
