# Generated by Django 4.1.3 on 2023-03-06 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruit", "0006_recruit_dday_recruit_likes_recruit_view_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recruit",
            old_name="view",
            new_name="views",
        ),
    ]
