# Generated by Django 4.1.3 on 2023-02-11 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['id'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
    ]
