# Generated by Django 4.1.3 on 2023-02-12 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['created'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
    ]
