# Generated by Django 4.1.3 on 2023-02-12 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_project_options_preview_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preview_image',
            old_name='project_id',
            new_name='project',
        ),
    ]
