# Generated by Django 4.1.3 on 2023-02-12 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_rename_project_id_preview_image_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preview_image',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previewImages', to='project.project'),
        ),
    ]
