# Generated by Django 4.1.3 on 2023-02-14 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_preview_image_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preview_image',
            name='image_url',
            field=models.ImageField(upload_to='project_image/{project.id}'),
        ),
    ]
