# Generated by Django 4.1.3 on 2023-02-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_hashtag_count_alter_preview_image_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preview_image',
            name='image_url',
            field=models.ImageField(upload_to='project_image'),
        ),
    ]
