# Generated by Django 4.1.3 on 2023-02-14 17:37

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_preview_image_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preview_image',
            name='image_url',
            field=models.ImageField(upload_to=project.models.get_img_storage_path),
        ),
    ]
