# Generated by Django 4.1.3 on 2023-02-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("created_At", models.DateTimeField(auto_now_add=True)),
                ("updated_At", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
