# Generated by Django 4.1.3 on 2023-02-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="user",
            field=models.CharField(default="익명", max_length=200),
        ),
    ]
