# Generated by Django 4.1.3 on 2023-04-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='username',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='users',
            name='social',
        ),
        migrations.AlterField(
            model_name='users',
            name='birthday',
            field=models.CharField(max_length=254),
        ),
    ]
